worker_processes  1;
pid /tmp/h5-app-nginx.pid;
error_log /tmp/h5-app-nginx-error.log;

events {
    worker_connections  1024;
}

http {
    include       /opt/homebrew/etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    tcp_nopush    on;
    access_log    /tmp/h5-app-nginx-access.log;

    gzip              on;
    gzip_vary         on;
    gzip_min_length   1024;
    gzip_comp_level   5;
    gzip_proxied      any;
    gzip_types
        text/plain
        text/css
        text/xml
        application/javascript
        application/x-javascript
        application/json
        application/xml
        application/xml+rss
        application/wasm
        image/svg+xml
        font/ttf
        font/otf
        font/woff
        font/woff2;

    server {
        listen 80;
        server_name app.maccms.cloud;
        root /Users/ec2-user/h5-app/maccms/out;
        index index.html;

        location / {
            try_files $uri $uri.html $uri/ /index.html;
        }

    }
}
